### ISSUE TITLE
Error in di:compile Magento 2.4

### ISSUE THREAD

**Issue by luancschmitz** [mundipagg/magento2#284]
### Status

BUG REPORT - This error only happens in Magento 2.4 +.

### Steps

1. Install Version 2.4.15-beta in a Magento 2.4
2. Run bin/magento setup:di:compile
3. The Error is displayed

### Expected behaviour

Setup:di:compile run with success!

### Actual behaviour

  Class Magento\Braintree\Helper\CcType does not exist

## Posible Soluction
Change the "Magento\Braintree\Helper\CcType" class to the "Paypal\Braintree\Helper\CcType" class in the Mundipagg\Mundipagg\Block\Adminhtml\Form\Field\CcTypes

### Environment

Magento Version: 2.4
PHP Version: 7.4.8

### Logs / Stack trace

```
In ClassReader.php line 43:

  Class Magento\Braintree\Helper\CcType does not exist

In ClassReader.php line 36:

  Class Magento\Braintree\Helper\CcType does not exist

```

**Comment by armandoleite** [comment]
Magento 2.4.x removed the Braintree module from the core and recommends that it be installed again https://docs.magento.com/user-guide/payment/braintree.html.

As the Mundipagg module makes use of the Braintree module (core), this generates an error because the class no longer exists.

I recommend updating the dependencies to the Magento standard "Magento \ Payment \ Model \ Source \ Cctype" and avoiding dependencies on third party modules.

**Comment by GabrielDeveloper** [comment]
Hi guys, 

We've already added this fix to our backlog and we're working to deliver a new version compatible with 2.4.* as soon as possible
